# -*- coding: utf-8 -*-
"""geo_cal_cmed

Automatically generated by Colaboratory.

"""

!pip install geopandas
!pip install geemap

import pandas as pd
import geopandas as gp
import geemap

from google.colab import drive
drive.mount('/content/gdrive')

c_tip_r = pd.read_csv('/content/gdrive/MyDrive/qgis/c_tip_rua.csv') #Arquivo com os nomes dos tipos de cobertura de solo e os respectivos coeficientes de runoff

cob_sol = gp.read_file('/content/gdrive/MyDrive/qgis/cob_sol_bc_p_a.shp') #Arquivo com o shapefile contendo os polígonos de bacia de contribuição com 
                                                                          #os valores de porcentagem de cada tipo de cobertura de solo presente na bacia

ruas_t = c_tip_r['rua']
ruas = []
for r in ruas_t:
    ruas.append(r) #Lista com os nomes de tipo de cobertura do solo da planilha de coeficiente de runoff
print(ruas)

len_ruas = len(ruas)
r_p = []
i = 0
while i < len_ruas:
  for c in list(cob_sol.columns):
    if ruas[i] in c and '_p' in c:
      r_p.append(c) #Lista com os nomes de tipo de cobertura do solo com a grafia definida pelos campos da tabela de atributos da camada de bacias de contribuição
  i=i+1

print(r_p)

for index in range(len(cob_sol)):
  cob_sol['Cmed'].iloc[index] = 0
  c = cob_sol['Cmed'].iloc[index]
  print(c)

for p in r_p:
  if ruas[0] in p:
    print(p)

print(len(cob_sol))

c_idx = c_tip_r.columns.get_loc('c')
for index in range(len(cob_sol)):
  it = 0
  while it < len_ruas:
    c_f = c_tip_r.iloc[it, c_idx]
    for p in r_p:
      if ruas[it] in p:
        cp = cob_sol[p].iloc[index]
        cmed = cob_sol['Cmed'].iloc[index]
        cmed = cmed + (cp/100)*c_f        #Cálculo do coeficiente de runoff médio para cada bacia de contribuição da camada
        cob_sol['Cmed'].iloc[index] = cmed
    it = it + 1

for ind in range(len(cob_sol)):
  cmed = cob_sol['Cmed'].iloc[ind]
  print(cmed)

cob_sol.to_file('/content/gdrive/MyDrive/qgis/cob_sol_bc_p_a_cmed.shp')
